### ISSUE TITLE
Racon fails to build on 1.5.0

### ISSUE THREAD

**Issue by schorlton** [lbcb-sci/racon#62]
Hi Robert,

I saw you just released a new racon and I tried to build but am now running into issues.  I'm pasting  a reproducible Dockerfile below. This Dockerfile worked on commit https://github.com/lbcb-sci/racon/commit/b591b12c22539948782704446989893bde826a29 and substituting ubuntu 20.04 for ubuntu 18.04 below. Any ideas? Thanks!!

Sam

Dockerfile:
```
FROM nvidia/cuda:11.4.2-devel-ubuntu20.04 AS builder

# Solve cmake asking for timezone: https://dev.to/setevoy/docker-configure-tzdata-and-timezone-during-build-20bk
ENV TZ=America/Vancouver
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG RACON_GIT_HASH=a2cfcac281d312a73912a97d6d960404f516c389
# Checkout git version: https://stackoverflow.com/q/3555107
RUN apt-get update && \
    apt-get install -y git cmake zlib1g-dev && \
    git clone --recursive https://github.com/lbcb-sci/racon.git racon && \
    cd racon && \
    git reset --hard ${RACON_GIT_HASH} && \
    git submodule update && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -Dracon_enable_cuda=ON .. && \
    make && \
    apt-get remove -y git cmake && \
    rm -rf /var/lib/apt/lists/*
```

Log:
```
Scanning dependencies of target gwbase
[  1%] Building CXX object _deps/genomeworks-build/common/base/CMakeFiles/gwbase.dir/src/cudautils.cpp.o
In file included from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/fmt/fmt.h:21,
                 from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/common.h:28,
                 from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/spdlog.h:12,
                 from /racon/build/_deps/genomeworks-src/common/base/include/claraparabricks/genomeworks/logging/logging.hpp:99,
                 from /racon/build/_deps/genomeworks-src/common/base/include/claraparabricks/genomeworks/utils/cudautils.hpp:22,
                 from /racon/build/_deps/genomeworks-src/common/base/src/cudautils.cpp:17:
/racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/fmt/bundled/format.h:3475:55: warning: ISO C++ did not adopt string literal operator templates taking an argument pack of characters [-Wpedantic]
 3475 | FMT_CONSTEXPR internal::udl_formatter<Char, CHARS...> operator""_format() {
      |                                                       ^~~~~~~~
[  3%] Building CXX object _deps/genomeworks-build/common/base/CMakeFiles/gwbase.dir/src/logging.cpp.o
In file included from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/fmt/fmt.h:21,
                 from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/common.h:28,
                 from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/spdlog.h:12,
                 from /racon/build/_deps/genomeworks-src/common/base/include/claraparabricks/genomeworks/logging/logging.hpp:99,
                 from /racon/build/_deps/genomeworks-src/common/base/src/logging.cpp:17:
/racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/fmt/bundled/format.h:3475:55: warning: ISO C++ did not adopt string literal operator templates taking an argument pack of characters [-Wpedantic]
 3475 | FMT_CONSTEXPR internal::udl_formatter<Char, CHARS...> operator""_format() {
      |                                                       ^~~~~~~~
[  5%] Building CXX object _deps/genomeworks-build/common/base/CMakeFiles/gwbase.dir/src/graph.cpp.o
[  7%] Linking CXX static library ../../../../lib/libgwbase.a
[  7%] Built target gwbase
[  9%] Building NVCC (Device) object _deps/genomeworks-build/cudaaligner/CMakeFiles/cudaaligner.dir/src/cudaaligner_generated_hirschberg_myers_gpu.cu.o
[ 11%] Building NVCC (Device) object _deps/genomeworks-build/cudaaligner/CMakeFiles/cudaaligner.dir/src/cudaaligner_generated_ukkonen_gpu.cu.o
[ 13%] Building NVCC (Device) object _deps/genomeworks-build/cudaaligner/CMakeFiles/cudaaligner.dir/src/cudaaligner_generated_myers_gpu.cu.o
Scanning dependencies of target cudaaligner
[ 15%] Building CXX object _deps/genomeworks-build/cudaaligner/CMakeFiles/cudaaligner.dir/src/cudaaligner.cpp.o
In file included from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/fmt/fmt.h:21,
                 from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/common.h:28,
                 from /racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/spdlog.h:12,
                 from /racon/build/_deps/genomeworks-src/common/base/include/claraparabricks/genomeworks/logging/logging.hpp:99,
                 from /racon/build/_deps/genomeworks-src/cudaaligner/src/cudaaligner.cpp:18:
/racon/build/_deps/genomeworks-src/3rdparty/spdlog/include/spdlog/fmt/bundled/format.h:3475:55: error: ISO C++ did not adopt string literal operator templates taking an argument pack of characters [-Werror=pedantic]
 3475 | FMT_CONSTEXPR internal::udl_formatter<Char, CHARS...> operator""_format() {
      |                                                       ^~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [_deps/genomeworks-build/cudaaligner/CMakeFiles/cudaaligner.dir/build.make:84: _deps/genomeworks-build/cudaaligner/CMakeFiles/cudaaligner.dir/src/cudaaligner.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1976: _deps/genomeworks-build/cudaaligner/CMakeFiles/cudaaligner.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
The command '/bin/sh -c apt-get update &&     apt-get install -y git cmake zlib1g-dev &&     git clone --recursive https://github.com/lbcb-sci/racon.git racon &&     cd racon &&     git reset --hard ${RACON_GIT_HASH} &&     git submodule update &&     mkdir build &&     cd build &&     cmake -DCMAKE_BUILD_TYPE=Release -Dracon_enable_cuda=ON .. &&     make &&     apt-get remove -y git cmake &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2
```

**Comment by rvaser** [comment]
Hi Sam,
I am able to compile with CUDA10.2 and GCC7.5.0. Which compiler versions are you using?

Best regards,
Robert

**Comment by schorlton** [comment]
> Hi Sam, I am able to compile with CUDA10.2 and GCC7.5.0. Which compiler versions are you using?
> 
> Best regards, Robert

Was using docker image `nvidia/cuda:11.4.2-devel-ubuntu20.04`, which contains CUDA 11.4.2, and `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`. Using `nvidia/cuda:10.2-devel-ubuntu18.04` fixes the compilation. I guess it doesn't work with newer CUDA or gcc...

Do you have recommended CUDA and gcc version to use for racon? The versions cited above?
Thanks for your help!

**Comment by rvaser** [comment]
Which gcc did you end up using? The compilation breaks in [GenomeWorks](https://github.com/clara-parabricks/GenomeWorks) submodule, I guess due to newer gcc versions (you can maybe try raising an issue there). We test with the versions stated in readme (below) and gcc-7.5.0/clang-9.0 (GPU build is not in CI but tested on local server with gcc-7.5.0).
```
Dependencies

    gcc 4.8+ or clang 3.4+
    cmake 3.2+
    zlib

CUDA Support

    gcc 5.0+
    cmake 3.10+
    CUDA 9.0+
```

**Comment by schorlton** [comment]
Docker image `nvidia/cuda:10.2-devel-ubuntu18.04` contains `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0` and it worked with that.

**Comment by kiwifb** [comment]
Really it is the same issue as #52. That issue doesn't exist anymore in https://github.com/clara-parabricks/GenomeWorks - you ship it as a third party frozen in 2020, and the problem is in a third party of GenomeWorks (does that make it a "9th party of Racon? :) ). That third party is not in GenomeWorks anymore.

I don't want to be dismissive, but you are basically telling us to work with a 4 years old version of ubuntu (and other parts that are about 2 or more years old) or use a container based on it (I guess that's what containers are for at least).

**Comment by rvaser** [comment]
I'll try to update it.

**Comment by kiwifb** [comment]
For the record on line https://github.com/lbcb-sci/racon/blob/master/CMakeLists.txt#L161 I replaced `v0.5.3` with `dev` and it compiled and installed properly. I have someone that promised to test it over the week end, so I wanted to wait before mentioning it.

I did go straight to `dev` because from previous experience compiling GenomeWorks, going for the last released version also had issues. Only `dev` worked.

**Comment by rvaser** [comment]
I tried the latest release, it compiles, but unit tests break with weird error. Can you please try and run racon_test? Some tests will fail due to small differences, but one test gives me a kernel error stating to choose a different banding mode (even though I am using BandMode::full_band). Error persists from version v2021.02.0 (first after v0.5.3).

**Comment by kiwifb** [comment]
I do have some errors
```
[ RUN      ] RaconPolishingTest.ConsensusWithQualitiesCUDA
Initialized GenomeWorks logger with log level WARN
Logger already initialized with log level WARN
Using 1 GPU(s) to perform polishing
Initialize device 0
[CUDAPolisher] Constructed.
[racon::Polisher::initialize] loaded target sequences 0.000723 s
[racon::Polisher::initialize] loaded sequences 0.037394 s
[racon::Polisher::initialize] loaded overlaps 0.000365 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.442154 s
[racon::Polisher::initialize] transformed data into windows 0.002113 s
[racon::CUDAPolisher::polish] allocated memory on GPUs for polishing 1.053868 s
[racon::CUDAPolisher::polish] polished windows on GPU 0.305305 s
[racon::CUDAPolisher::polish] generated consensus 0.000209 s
/home/rccadmin/racon/test/racon_test.cpp:316: Failure
Expected equality of these values:
  1385
  calculateEditDistance( polished_sequences[0]->reverse_complement(), reference[0]->data())
    Which is: 1390
[racon::Polisher::] total = 2.182643 s
[  FAILED  ] RaconPolishingTest.ConsensusWithQualitiesCUDA (47758 ms)
[ RUN      ] RaconPolishingTest.ConsensusWithoutQualitiesCUDA
Logger already initialized with log level WARN
Logger already initialized with log level WARN
Using 1 GPU(s) to perform polishing
Initialize device 0
[CUDAPolisher] Constructed.
[racon::Polisher::initialize] loaded target sequences 0.000553 s
[racon::Polisher::initialize] loaded sequences 0.019761 s
[racon::Polisher::initialize] loaded overlaps 0.000274 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.406471 s
[racon::Polisher::initialize] transformed data into windows 0.000400 s
[racon::CUDAPolisher::polish] allocated memory on GPUs for polishing 0.932483 s
[racon::CUDAPolisher::polish] polished windows on GPU 0.349760 s
[racon::CUDAPolisher::polish] generated consensus 0.000275 s
/home/rccadmin/racon/test/racon_test.cpp:339: Failure
Expected equality of these values:
  1607
  calculateEditDistance( polished_sequences[0]->reverse_complement(), reference[0]->data())
    Which is: 1599
[racon::Polisher::] total = 2.376109 s
[  FAILED  ] RaconPolishingTest.ConsensusWithoutQualitiesCUDA (2378 ms)
[ RUN      ] RaconPolishingTest.ConsensusWithQualitiesAndAlignmentsCUDA
Logger already initialized with log level WARN
Logger already initialized with log level WARN
Using 1 GPU(s) to perform polishing
Initialize device 0
[CUDAPolisher] Constructed.
[racon::Polisher::initialize] loaded target sequences 0.000809 s
[racon::Polisher::initialize] loaded sequences 0.054236 s
[racon::Polisher::initialize] loaded overlaps 0.032535 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.003534 s
[racon::Polisher::initialize] transformed data into windows 0.002863 s
[racon::CUDAPolisher::polish] allocated memory on GPUs for polishing 1.709781 s
[racon::CUDAPolisher::polish] polished windows on GPU 0.275786 s
[racon::CUDAPolisher::polish] generated consensus 0.000278 s
/home/rccadmin/racon/test/racon_test.cpp:362: Failure
Expected equality of these values:
  1541
  calculateEditDistance( polished_sequences[0]->reverse_complement(), reference[0]->data())
    Which is: 1599
[racon::Polisher::] total = 2.424614 s
[  FAILED  ] RaconPolishingTest.ConsensusWithQualitiesAndAlignmentsCUDA (2427 ms)
[ RUN      ] RaconPolishingTest.ConsensusWithoutQualitiesAndWithAlignmentsCUDA
Logger already initialized with log level WARN
Logger already initialized with log level WARN
Using 1 GPU(s) to perform polishing
Initialize device 0
[CUDAPolisher] Constructed.
[racon::Polisher::initialize] loaded target sequences 0.000561 s
[racon::Polisher::initialize] loaded sequences 0.018140 s
[racon::Polisher::initialize] loaded overlaps 0.020911 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.003771 s
[racon::Polisher::initialize] transformed data into windows 0.000390 s
[racon::CUDAPolisher::polish] allocated memory on GPUs for polishing 1.403760 s
[racon::CUDAPolisher::polish] polished windows on GPU 0.343251 s
[racon::CUDAPolisher::polish] generated consensus 0.000267 s
/home/rccadmin/racon/test/racon_test.cpp:385: Failure
Expected equality of these values:
  1661
  calculateEditDistance( polished_sequences[0]->reverse_complement(), reference[0]->data())
    Which is: 1808
[racon::Polisher::] total = 2.250993 s
[  FAILED  ] RaconPolishingTest.ConsensusWithoutQualitiesAndWithAlignmentsCUDA (2254 ms)
[ RUN      ] RaconPolishingTest.ConsensusWithQualitiesLargerWindowCUDA
Logger already initialized with log level WARN
Logger already initialized with log level WARN
Using 1 GPU(s) to perform polishing
Initialize device 0
[CUDAPolisher] Constructed.
[racon::Polisher::initialize] loaded target sequences 0.000647 s
[racon::Polisher::initialize] loaded sequences 0.043941 s
[racon::Polisher::initialize] loaded overlaps 0.000474 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.406692 s
[racon::Polisher::initialize] transformed data into windows 0.003083 s
[racon::CUDAPolisher::polish] allocated memory on GPUs for polishing 1.388942 s
[racon::CUDAPolisher::polish] polished windows on GPU 0.457947 s
[racon::CUDAPolisher::polish] generated consensus 0.000412 s
/home/rccadmin/racon/test/racon_test.cpp:408: Failure
Expected equality of these values:
  4168
  calculateEditDistance( polished_sequences[0]->reverse_complement(), reference[0]->data())
    Which is: 4402
[racon::Polisher::] total = 2.912576 s
[  FAILED  ] RaconPolishingTest.ConsensusWithQualitiesLargerWindowCUDA (2915 ms)
[ RUN      ] RaconPolishingTest.ConsensusWithQualitiesEditDistanceCUDA
Logger already initialized with log level WARN
Logger already initialized with log level WARN
Using 1 GPU(s) to perform polishing
Initialize device 0
[CUDAPolisher] Constructed.
[racon::Polisher::initialize] loaded target sequences 0.000743 s
[racon::Polisher::initialize] loaded sequences 0.049397 s
[racon::Polisher::initialize] loaded overlaps 0.000477 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.367371 s
[racon::Polisher::initialize] transformed data into windows 0.002265 s
[racon::CUDAPolisher::polish] allocated memory on GPUs for polishing 1.301916 s
[racon::CUDAPolisher::polish] polished windows on GPU 0.271971 s
[racon::CUDAPolisher::polish] generated consensus 0.000256 s
/home/rccadmin/racon/test/racon_test.cpp:431: Failure
Expected equality of these values:
  1361
  calculateEditDistance( polished_sequences[0]->reverse_complement(), reference[0]->data())
    Which is: 1389
[racon::Polisher::] total = 2.500921 s
[  FAILED  ] RaconPolishingTest.ConsensusWithQualitiesEditDistanceCUDA (2503 ms)
```
`racon_test` is still going but seems to be stuck
```
[ RUN      ] RaconPolishingTest.FragmentCorrectionWithoutQualitiesFullCUDA
Logger already initialized with log level WARN
Logger already initialized with log level WARN
Using 1 GPU(s) to perform polishing
Initialize device 0
[CUDAPolisher] Constructed.
[racon::Polisher::initialize] loaded target sequences 0.019307 s
[racon::Polisher::initialize] loaded sequences 0.019286 s
[racon::Polisher::initialize] loaded overlaps 0.008183 s
[racon::Polisher::initialize] aligning overlaps [====================] 7.851069 s
[racon::Polisher::initialize] transformed data into windows 0.034468 s
[racon::CUDAPolisher::polish] allocated memory on GPUs for polishing 1.074444 s
[WARN /home/rccadmin/racon/build/_deps/genomeworks-src/cudapoa/src/cudapoa_batch.cuh:451] Kernel Error: Traceback in Needleman-Wunsch algorithm failed. in batch 8
Suggestion  : You may retry with a different banding mode.
[racon::CUDAPolisher::polish] generating consensus [==>                 ] 0.310851 s
```
GPU is going as far as I can tell
```
nvidia-smi 
Sat Feb 26 21:08:53 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:0B:00.0 Off |                    0 |
| N/A   32C    P0    43W / 250W |  14585MiB / 16384MiB |     97%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     83920      C   ./racon_test                    14577MiB |
+-----------------------------------------------------------------------------+
```

**Comment by kiwifb** [comment]
I had to interrupt that last one. It wasn't going anywhere.

**Comment by rvaser** [comment]
Same thing happens to me. I raised an [issue](https://github.com/clara-parabricks/GenomeWorks/issues/666) on GenomeWorks. Thanks for verifying!

**Comment by znruss** [comment]
Sorry about the premature pull request earlier - I also got around to running some tests and have encountered the same issue on both an RTX 2060 and a A100, with CUDA 11.1 and 11.6. Exact same error.
